# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            I like Gary Johnson but...
tagline:          'I got some questions'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Matt Crum'
  url:            https://twitter.com/mattscottcrum

paginate:         50

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mattcrum
